<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%><!DOCTYPE html>
<%@include file="../includes/header.jsp" %>

<!-- Page Heading -->

<h1 class="mt-4">FREE BOARD PAGE</h1>
<div class="card mb-4">

	<div class="card-header">
		<i class="fas fa-table mr-1"></i> 자주 묻는 질문
	</div>
	<div class="card-body">
		<div class="table-responsive">
			<table class="table table-bordered" id="dataTable" width="100%"
				cellspacing="0">
				<thead>
					<tr>
						<th>머릿말</th>
						<th>제목</th>
						<th>작성자</th>
						<th>작성일</th>
						<th>조회수</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
					<tr>
						<td>가입인사</td>
						<td>반갑습니다</td>
						<td>강서마곡</td>						
						<td>2021-04-05</td>
						<td>134</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<%@include file="../includes/footer.jsp" %>

